### PR TITLE
Backport #20 to version 1.x of the GEM

### PR DESCRIPTION
**Pull request by pinkahd**
Hey 👋🏼 

We've encountered some issues when we've updated our `sidekiq-unique-jobs` gem to the latest version and it looks like the latest version started sending nested fields issue related https://github.com/iMacTia/sidekiq-logstash/issues/3 Currently we're still stuck on version 5 of Sidekiq so we couldn't update the `sidekiq-logstash` gem to version 2.x to get this patch in.

This patch is back porting the fix made in https://github.com/iMacTia/sidekiq-logstash/pull/20 to version 1.x as well, I'm thinking there might be other in the same situations that might benefit form this patch as well.

Let me know if you're still interested to support version 1.x of this gem if not I can close this PR and maintain our fork for now.

Thanks

### CODE REVIEW

**Comment by iMacTia** [comment]
Hi @pinkahd, thanks for opening this.
I have nothing against back porting this fix and releasing a `1.2.1` version.
To do this, I've created a 1.x branch and set that as the base branch, however GitHub is not running the CI tests for some reason. Could you try pushing another commit to the PR, e.g. setting the `ruby-version` to 2.6.6?
Hopefully that will be enough to trigger the CI run

**Comment by pinkahd** [comment]
Pushed a commit to increase ruby version to 2.6.6 

I believe the reason why CI isn't running it's because I'm a first time contributor.

Screenshot 2021-06-21 at 16 54 54

**Comment by iMacTia** [comment]
> I believe the reason why CI isn't running it's because I'm a first time contributor.

Correct, but GitHub was not showing me the "Approve and run CI" button, so I couldn't approve.
It did after your latest commit, as I imagined 😉 
CI is running now 🙌 !

**Comment by iMacTia** [comment]
@pinkahd minor rubocop offenses to fix, should be easy but please let me know if you need help 👍

**Comment by pinkahd** [comment]
Thanks 🙌🏼 I'll fix those and update the branch.

**Comment by pinkahd** [comment]
@iMacTia Looks like you'll need to approve the CI again after I've force update the branch, hopefully this this everything will pass 🤞🏼

**Comment by iMacTia** [comment]
Mmmh something is wrong with `bundle` apparently, I noticed [this line](https://github.com/iMacTia/sidekiq-logstash/pull/23/checks?check_run_id=2877069621#step:3:9) in the logs.

**Comment by pinkahd** [comment]
> Mmmh something is wrong with `bundle` apparently, I noticed [this line](https://github.com/iMacTia/sidekiq-logstash/pull/23/checks?check_run_id=2877069621#step:3:9) in the logs.

Hmm noticed that as well, could it be because of the depreciated `actions/setup-ruby@v1` and version 2.5.x didn't had bundler installed 🤔

**Comment by pinkahd** [comment]
I think that was it, all checks passed with the new `setup-ruby` action 🎉

**Comment by iMacTia** [comment]
Thanks for fixing that @pinkahd, all green now 🎉 ! LGTM

**Comment by pinkahd** [comment]
Thanks 🙌🏼 Let me know if you're gonna release version 1.2.1 in ruby gems 😇. Thanks again 💯

**Comment by iMacTia** [comment]
https://rubygems.org/gems/sidekiq-logstash/versions/1.2.1 🎉

**Comment by pinkahd** [comment]
Amazing! 🎉

**Pull request merged**
