### PR TITLE
feat(job_start_log): flag to enable logging of job start

### LINKED ISSUE #4: Add logging when job starts
I noticed sidekiq-logstash doesn't log an event when a job starts: https://github.com/iMacTia/sidekiq-logstash/blob/e3a5c706a77ea1559f5379e14b5b34f3bea2d552/lib/sidekiq/middleware/server/logstah_logging.rb#L12

That seems like valuable information. Is there any reason this isn't being done?

### PR DESCRIPTION
**Pull request by mdibaiee**
fixes #4

### CODE REVIEW

**Comment by mdibaiee** [comment]
@iMacTia Thanks. I agree tests would be great. I just noticed there seems to be seemingly duplicate code over [here](https://github.com/iMacTia/sidekiq-logstash/blob/master/lib/sidekiq/logstash_job_logger.rb) and [here](https://github.com/iMacTia/sidekiq-logstash/blob/master/lib/sidekiq/middleware/server/logstash_logging.rb). I have changed the first one only now, and my manual tests were fine (Sidekiq was indeed logging start of jobs). I'm wondering how these two pieces of code related to each other.

**Comment by iMacTia** [comment]
@mdibaiee thanks for adding the tests and for pointing out the code duplication.
I checked the history and I noticed it was introduced with this [commit](https://github.com/iMacTia/sidekiq-logstash/commit/e7f2e71191aceaf16d8b31991c5b6c77cb4e7abf#diff-9b474012fcbe616d36457d9a44efe559)
I'm quite sure one of the two file is a leftover at this point, but will require additional checks before removing it, so don't worry about it for now 👍, I'll open an issue for it.

I'll review this PR again now

**Comment by mdibaiee** [comment]
Thanks @iMacTia . I just addd a test case for "not logging" a job_start log by default. :+1:

**Comment by silviusimeria** [comment]
Hi guys,

The logging server middleware was removed in Sidekiq 5.0.0, see: https://github.com/mperham/sidekiq/blob/master/Changes.md

If I remember correctly, when I added support for sidekiq 5,  the common logging logic was moved in`Sidekiq::Logging::Shared`, but some parts remained duplicated because I wanted this gem to support older sidekiq versions through the middleware approach.

If you want to port the job start log to older sidekiq versions you might need to change the middleware part too.

**Comment by mdibaiee** [comment]
@iMacTia so, what's new here? do I need to make additional changes?

**Comment by iMacTia** [comment]
@mdibaiee: @silviusimeria point was that the changes you did to `logstash_job_logger.rb` needs to be done to `server/logstash_logging.rb` as well if you want to support `Sidekiq < 5.0`.
If this is something you're not interested in, I can always merge your PR and we can extend the feature to older versions of Sidekiq on a separate PR. Just let me know :)

**Comment by mdibaiee** [comment]
@iMacTia I see, we use Sidekiq-5.x.x, so I think we're good with the current functionality. Testing the change on older Sidekiq versions would also be of additional effort and I would rather skip that. :grin:

Looking forward to using this in our production system :rocket:

**Comment by iMacTia** [comment]
@mdibaiee sure no problem! Thanks for contributing!
I’ll merge this so you can use master branch in the meantime, but I’d rather get the older versions and code duplication fixed before releasing a proper version.
Hopefully I’ll be able to look at it sometime this or next week :)
Cc @silviusimeria

**Pull request merged**
