### PR TITLE
Change exceptions logging: Add logging of exceptions' causes

### PR DESCRIPTION
**Pull request by dominh**
This pull request adds logging for `Exception#cause`

### CODE REVIEW

**Review by iMacTia — CHANGES_REQUESTED** [review]
Hi @dominh and thank you for the contribution.
I really like the idea of exposing the `cause` from the exception as that can sometimes provide useful information about what happened. I have a few of concerns with the change as-is right now though:
1. The output structure is changed in a backwards-incompatible way: we're moving from a flat, 3-fields structure to a multi-level one. People might be relying on the older structure and have their observability platforms configured with monitors and alerts, so we can't just change it like that unfortunately. A few options on how we could address this:
   * Keep both the old and new structure, add a config setting to pick which one to use (defaults to OLD)
   * Add a new `error_cause` field to the payload alongside the 3 existing ones. Since this is an entirely new field, this CAN be multi-level so you could have the same recursive `error_cause: { class:, message:, backtrace:, cause: }`
1. The recursion is uncapped; this could have various unintended side-effects. Some observability systems may struggle with too many levels of data, and the log line size could go over the transfer/ingestion limit (e.g. Datadog has a hard limit of 1MB, but a suggested soft limit of 25KB).
   * My suggestion here would be to cap the recursion to 1-2 levels deep. I doubt you'll need more than that under normal circumstances. This could also be made into a setting later if we need to provide more flexibility.

**Comment by dominh** [comment]
I pushed new changes addressing your concerns.
I chose to keep both the old and new structure and added a config that allows user to chose one. The "hybrid" but backward compatible log seems to me more complex which is unnecessary I think.
I added `causes_logging_max_depth` config with 2 as default. Personally I'm going to set it to higher values in my projects as I like to have errors logged as verbosely as possible.

**Review by iMacTia — APPROVED** [review]
Thank you for addressing my comments @dominh 🙏 
I also prefer the approach of having 2 separate but configurable behaviours.
I believe adding the `exception_cause` to the legacy behaviour would have also been a nice addition, but appreciate this is not a priority for you so I'll do it myself in a follow-up PR 🙂

**Comment by iMacTia** [comment]
Inspired by this change, I've opened #39 🙌

**Pull request merged**
